remote_theme: daviddarnes/alembic

# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
# twitter:
#   username: DavidDarnes # jekyll-seo-tag > Owners twitter username
author: Incotroceni # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Asociația Incotroceni # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://www.facebook.com/incotroceni
    - https://github.com/incotroceni

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/Bucharest # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Postări # Needed for Siteleaf
    output: true
    description: "Ultimele știri din cartier" # The post list page content
    feature_text: |
      Bine ați venit Incotroceni!
    feature_image: "https://picsum.photos/2560/600?image=866"

  evenimente:
    title: Evenimente Incotroceni
    output: true

  proiecte:
    title: Proiecte Incotroceni
    output: true

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/images/logo.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: ro-RO # Set the site language
title: "Asociația Incotroceni" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/images/logo.png" # Site logo, also used in jekyll-seo-tag
description: "Site-ul oficial al Asociației Incotroceni. Ultimele știri și evenimente din cartierul Cotroceni." # Site description and default description, also used in jekyll-seo-tag
url: "https://incotroceni.ro" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/incotroceni/incotroceni.github.io"
email: "salut@incotroceni.ro"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
avatarurl: "/favicon.png"
google_analytics: 'UA-118125506-1'
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site navigation
navigation_header:
  Acasă: /
  Implică-te: /implica-te/
  Evenimente: /evenimente/
  Despre: /despre/
  Contact: /contact/
  Donează: /doneaza/

navigation_footer:
  Abonare la noutăți: http://eepurl.com/ck0bNf
  Implică-te: /implica-te/

social_links:
   Facebook: https://facebook.com/incotroceni
   Instagram: https://instagram.com/incotroceni
   Youtube: https://www.youtube.com/channel/UCihlndbN0dSh4LEuZ4FPcrQ

sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
  #Twitter: "#0d94e7"
  #facebook: "#3B5998"
  # Google+: "#DC4E41"
  # Pinterest: "#BD081C"
  # LinkedIn: "#0077B5"
  # tumblr: "#36465D"
  # Reddit: "#FF4500"
  # Hacker News: "#ff6600"
  # Designer News: "#2D72D9"
  #Email: "#2D72D9"
